# Dependabot configuration for CloudWorkstation
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    # Group all minor and patch updates together
    groups:
      aws-sdk-dependencies:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # For pre-1.0.0 versions, ignore patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        versions: ["0.x.x"]
    
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"