# CloudWorkstation golangci-lint configuration
# Compatible with golangci-lint v2.5+

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
    - .git
    - cmd/cws-gui/frontend

output:
  format: colored-line-number

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional useful linters
    - bodyclose
    - cyclop        # cyclomatic complexity
    - gocognit      # cognitive complexity
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gosec:
    excludes: []

  revive:
    confidence: 0.8

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - cyclop
        - errcheck
        - gosec
        - goconst

    # Allow complex main functions
    - path: cmd/.*/main\.go
      linters:
        - gocognit
        - cyclop