repos:
  # Standard file checks (fast)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict

  # Go formatting only (fast, auto-fixable)
  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        language: system
        entry: sh -c 'gofmt -w . && goimports -w .'
        types: [go]
        pass_filenames: false
        fail_fast: true

      - id: go-mod-tidy
        name: Go Mod Tidy
        language: system
        entry: go mod tidy
        types: [go]
        pass_filenames: false

# REMOVED from pre-commit (moved to make targets):
#   - golangci-lint (use: make lint)
#   - go test (use: make test-unit)
#   - coverage check (use: make test-coverage)
#   - gosec (use: make security)
#   - govulncheck (use: make security)
#
# Run before pushing:
#   make lint              # Comprehensive linting
#   make test-unit         # Fast unit tests
#   make test-smoke        # Critical path verification
#   make test-regression   # Full regression suite
