{% set name = "cloudworkstation" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/scttfrdmn/cloudworkstation/releases/download/v{{ version }}/cloudworkstation-linux-amd64.tar.gz  # [linux64]
    sha256: REPLACE_WITH_ACTUAL_CHECKSUM_LINUX_AMD64  # [linux64]
  - url: https://github.com/scttfrdmn/cloudworkstation/releases/download/v{{ version }}/cloudworkstation-linux-arm64.tar.gz  # [aarch64]
    sha256: REPLACE_WITH_ACTUAL_CHECKSUM_LINUX_ARM64  # [aarch64]
  - url: https://github.com/scttfrdmn/cloudworkstation/releases/download/v{{ version }}/cloudworkstation-darwin-amd64.tar.gz  # [osx and x86_64]
    sha256: REPLACE_WITH_ACTUAL_CHECKSUM_DARWIN_AMD64  # [osx and x86_64]
  - url: https://github.com/scttfrdmn/cloudworkstation/releases/download/v{{ version }}/cloudworkstation-darwin-arm64.tar.gz  # [osx and arm64]
    sha256: REPLACE_WITH_ACTUAL_CHECKSUM_DARWIN_ARM64  # [osx and arm64]
  - url: https://github.com/scttfrdmn/cloudworkstation/releases/download/v{{ version }}/cloudworkstation-windows-amd64.zip  # [win]
    sha256: REPLACE_WITH_ACTUAL_CHECKSUM_WINDOWS  # [win]

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin  # [unix]
    - cp cws $PREFIX/bin/  # [unix]
    - cp cwsd $PREFIX/bin/  # [unix]
    - mkdir -p $PREFIX/bin  # [win]
    - copy cws.exe %PREFIX%\\bin\\  # [win]
    - copy cwsd.exe %PREFIX%\\bin\\  # [win]

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - cws --version
    - cwsd --version

about:
  home: https://github.com/scttfrdmn/cloudworkstation
  license: MIT
  license_file: LICENSE
  summary: Launch cloud research environments in seconds
  description: |
    CloudWorkstation helps researchers and scientists create pre-configured
    cloud workstations optimized for their specific research needs.
    
    New in v0.4.2:
    - GUI interface with system tray integration
    - Real-time status monitoring
    - Cross-platform support (Windows, macOS, Linux)
    - Visual design system with consistent UI elements
    - Enhanced security with device binding
  doc_url: https://docs.cloudworkstation.org
  dev_url: https://github.com/scttfrdmn/cloudworkstation

extra:
  recipe-maintainers:
    - scttfrdmn