blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/scttfrdmn/cloudworkstation/tree/main/docs
    about: Read the user guides, architecture docs, and persona walkthroughs
  - name: 💬 Discussions
    url: https://github.com/scttfrdmn/cloudworkstation/discussions
    about: Ask questions and discuss ideas with the community
