name: Dependency Scanning

on:
  push:
    branches: [main]
    paths:
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [main]
    paths:
      - 'go.mod'
      - 'go.sum'
  schedule:
    - cron: '0 4 * * 1'  # Every Monday at 4:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  govulncheck:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

  osv-scanner:
    name: OSV Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner@v1
        with:
          to-scan: go.mod

  sbom-generation:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: cloudworkstation-sbom.spdx.json
          
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact
          path: cloudworkstation-sbom.spdx.json
          retention-days: 90